receivers:
  # OpenTelemetry receivers
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  # 你的自定义处理器
  groupbytrace:
    wait_duration: 2s
    num_traces: 1000

  tail_sampling:
    sample_rate: 0.9
    buffer_size: 4000
    pool_height: 1000
    combination_count: 100
    decision_wait: 2s

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      # 接收从jaeger-agent转发的OTLP数据
      receivers: [otlp]
      # 使用你的自定义处理器
      processors: [groupbytrace, tail_sampling]
      exporters: [debug]
